
@hostname = http://localhost:5000
@resettoken = "c64974aac6f9ea2edd4fb61a401c0e19b3205f7d"

@password = "password"


### 
GET {{hostname}}/api/address/1
Content-Type: application/json

### 
GET {{hostname}}/api/factures
Content-Type: application/json


###
POST {{hostname}}/api/users/login
Content-Type: application/json

{
    "email": "stefan@exemple.be",
    "password": "password"
}

###
GET {{hostname}}/api/products 

###
GET {{hostname}}/api/products/2

###
GET {{hostname}}/api/categories

###
GET {{hostname}}/api/roles

### 
DELETE {{hostname}}/api/orders/1

### ALLERGENS
GET {{hostname}}/api/allergens


### INVOICES
GET {{hostname}}/api/invoices
Content-Type: application/json 

### INVOICES BY ID
GET {{hostname}}/api/invoices/2


### DELETE INVOICE
DELETE {{hostname}}/api/invoices/4

###
GET {{hostname}}/api/authentification
Content-Type: application/json

{
    "resettoken": "123"
}

###
PUT {{hostname}}/api/authentification/resetpassword
Content-Type: application/json

{
    "token": "c64974aac6f9ea2edd4fb61a401c0e19b3205f7d",
    "password":123
}






###
POST {{hostname}}/api/users/login 
Content-Type: application/json

{
    "email": "root@exemple.be",
    "password": "password"
}


###
POST {{hostname}}/api/users/ 
Content-Type: application/json

{
    "first_name": "michel",
    "last_name": "michel",
    "email":"michel@exemple.com",
    "password": "password"
    
}





