export const ALLERGEN_LIST_REQUEST = 'ALLERGEN_LIST_REQUEST'
export const ALLERGEN_LIST_SUCCESS = 'ALLERGEN_LIST_SUCCESS'
export const ALLERGEN_LIST_FAIL = 'ALLERGEN_LIST_FAIL'

export const ALLERGEN_CREATE_REQUEST = 'ALLERGEN_CREATE_REQUEST'
export const ALLERGEN_CREATE_SUCCESS = 'ALLERGEN_CREATE_SUCCESS'
export const ALLERGEN_CREATE_FAIL = 'ALLERGEN_CREATE_FAIL'
export const ALLERGEN_CREATE_RESET = "ALLERGEN_CREATE_RESET"


export const ALLERGEN_DELETE_REQUEST = 'ALLERGEN_DELETE_REQUEST'
export const ALLERGEN_DELETE_SUCCESS = 'ALLERGEN_DELETE_SUCCESS'
export const ALLERGEN_DELETE_FAIL = 'ALLERGEN_DELETE_FAIL'