export const USER_MESSAGE_REQUEST = "USER_DELETE_REQUEST"
export const USER_MESSAGE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_MESSAGE_FAIL = "USER_DELETE_FAIL"
export const USER_MESSAGE_RESET = "USER_DELETE_RESET"
