export const ADMIN_USERSINVOICELIST_REQUEST = "ADMIN_USERSINVOICELIST_REQUEST"
export const ADMIN_USERINVOICESLIST_SUCCESS = "ADMIN_USERINVOICESLIST_SUCCESS"
export const ADMIN_USERINVOICESLIST_FAIL = "ADMIN_USERINVOICESLIST_FAIL"


export const ADMIN_USERINVOICE_REQUEST = "ADMIN_USERINVOICE_REQUEST"
export const ADMIN_USERINVOICE_SUCCESS = "ADMIN_USERINVOICE_SUCCESS"
export const ADMIN_USERINVOICE_FAIL = "ADMIN_USERINVOICE_FAIL"



export const ADMIN_DELETEINVOICE_REQUEST = "ADMIN_DELETEINVOICE_REQUEST"
export const ADMIN_DELETEINVOICE_SUCCESS = "ADMIN_DELETEINVOICE_SUCCESS"
export const ADMIN_DELETEINVOICE_FAIL = "ADMIN_DELETEINVOICE_FAIL"









