export const ADMIN_USERSLIST_REQUEST = "ADMIN_USERSLIST_REQUEST"
export const ADMIN_USERSLIST_SUCCESS = "ADMIN_USERSLIST_SUCCESS"
export const ADMIN_USERSLIST_FAIL = "ADMIN_USERSLIST_FAIL"


export const ADMIN_USERREVIEW_REQUEST = "ADMIN_USERREVIEW_REQUEST"
export const ADMIN_USERREVIEW_SUCCESS = "ADMIN_USERREVIEW_SUCCESS"
export const ADMIN_USERREVIEW_FAIL = "ADMIN_USERREVIEW_FAIL"



export const ADMIN_DELETEREVIEW_REQUEST = "ADMIN_DELETEREVIEW_REQUEST"
export const ADMIN_DELETEREVIEW_SUCCESS = "ADMIN_DELETEREVIEW_SUCCESS"
export const ADMIN_DELETEREVIEW_FAIL = "ADMIN_DELETEREVIEW_FAIL"
export const ADMIN_DELETEREVIEW_RESET = "ADMIN_DELETEREVIEW_RESET"




